from dataclasses import dataclass
from numba.experimental import jitclass
from .compiler import map_python_type_to_numba

def jitdataclass(cls):
    """
    A smart decorator that turns standard Python @dataclasses into high-performance 
    Numba @jitclass C-structs.
    
    It safely strips incompatible Python magic methods generated by dataclass 
    and automatically translates PEP-484 type hints into Numba internal types.
    """
    # Ensure it behaves like a standard dataclass in memory
    if not hasattr(cls, '__dataclass_fields__'):
        cls = dataclass(cls)
        
    spec = []
    # Translate python hints to numba types
    for field_name, py_type in cls.__annotations__.items():
        nb_type = map_python_type_to_numba(py_type)
        if nb_type is None:
            raise ValueError(f"Unsupported type {py_type} for field {field_name} in {cls.__name__}")
        spec.append((field_name, nb_type))
        
    # Generate a lightweight C-compatible __init__ dynamically
    args_str = ", ".join(f"{name}" for name in cls.__annotations__)
    assign_str = "\n    ".join(f"self.{name} = {name}" for name in cls.__annotations__)
    
    init_code = f"def __init__(self, {args_str}):\n    {assign_str}"
    local_env = {}
    exec(init_code, {}, local_env)
    
    # Create a pristine class dictionary without dataclass internals that crash Numba
    clean_dict = {'__init__': local_env['__init__']}
    
    for name, attr in cls.__dict__.items():
        # Strip python magics and dunders that Numba LLVM engine cannot compile
        if name not in ['__dataclass_params__', '__dataclass_fields__', '__match_args__', 
                        '__dict__', '__weakref__', '__annotations__', '__hash__',
                        '__repr__', '__eq__', '__init__']:
            # Strip default value definitions (which conflict with struct layouts)
            if name not in cls.__annotations__:
                clean_dict[name] = attr

    # Spawn the fresh class in memory
    CleanClass = type(cls.__name__, (), clean_dict)
    
    # Delegate to Numba's struct compiler
    return jitclass(spec)(CleanClass)
