"""Render an AnalysisResult as a self-contained HTML report.

No external assets/CDN — everything (CSS) is inlined, so the file opens
correctly straight from disk or an email attachment. Meant for demos and
one-off sharing, not as a served dashboard.
"""

from __future__ import annotations

import html

from .analysis import AnalysisResult

_SEVERITY_COLORS = {
    "LOW": "#6b7280",
    "MEDIUM": "#d97706",
    "HIGH": "#dc2626",
    "CRITICAL": "#991b1b",
}

_CSS = """
body { font-family: -apple-system, Helvetica, Arial, sans-serif; max-width: 900px;
       margin: 40px auto; padding: 0 20px; color: #1f2937; background: #fff; }
h1 { font-size: 22px; } h2 { font-size: 16px; margin-top: 32px; color: #374151; }
.summary { color: #4b5563; }
.cards { display: flex; gap: 16px; margin: 20px 0; flex-wrap: wrap; }
.card { border: 1px solid #e5e7eb; border-radius: 8px; padding: 12px 16px; min-width: 140px; }
.card .label { font-size: 12px; color: #6b7280; text-transform: uppercase; }
.card .value { font-size: 22px; font-weight: 600; }
table { border-collapse: collapse; width: 100%; margin-top: 8px; }
th, td { text-align: left; padding: 8px 10px; border-bottom: 1px solid #e5e7eb; font-size: 13px; }
th { color: #6b7280; font-weight: 600; }
.badge { display: inline-block; padding: 2px 8px; border-radius: 999px; color: #fff; font-size: 11px; font-weight: 600; }
footer { margin-top: 40px; color: #9ca3af; font-size: 12px; }
"""


def _esc(value: object) -> str:
    return html.escape(str(value))


def render_html(result: AnalysisResult, company_name: str = "") -> str:
    metrics = result.metrics
    title = f"cloudsealed-jit — {company_name}" if company_name else "cloudsealed-jit"

    anomaly_rows = "".join(
        f"<tr><td>{_esc(a.date)}</td>"
        f"<td><span class='badge' style='background:{_SEVERITY_COLORS.get(a.severity, '#6b7280')}'>"
        f"{_esc(a.severity)}</span></td>"
        f"<td>{a.zScore:.1f}</td><td>{a.deviation:+.1f}%</td><td>{_esc(a.description)}</td></tr>"
        for a in result.anomalies
    )
    recommendation_rows = "".join(
        f"<tr><td>{_esc(r.title)}</td><td>{r.potentialSavings:,.2f}/30d</td>"
        f"<td>{_esc(r.effort)}</td><td>{_esc(r.description)}</td></tr>"
        for r in result.recommendations
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{_esc(title)}</title>
<style>{_CSS}</style>
</head>
<body>
<h1>{_esc(title)}</h1>
<p class="summary">{_esc(result.summary)}</p>
<div class="cards">
  <div class="card"><div class="label">Waste</div><div class="value">{metrics.wastePercentage:.1f}%</div></div>
  <div class="card"><div class="label">Avg daily cost</div><div class="value">{metrics.averageDailyCost:,.2f}</div></div>
  <div class="card"><div class="label">Stability</div><div class="value">{metrics.sharpeRatio:.2f}</div></div>
  <div class="card"><div class="label">Anomalies</div><div class="value">{len(result.anomalies)}</div></div>
</div>
<h2>Anomalies</h2>
<table>
<tr><th>Date</th><th>Severity</th><th>z-score</th><th>Deviation</th><th>Description</th></tr>
{anomaly_rows or '<tr><td colspan="5">None found.</td></tr>'}
</table>
<h2>Recommendations</h2>
<table>
<tr><th>Title</th><th>Potential savings</th><th>Effort</th><th>Description</th></tr>
{recommendation_rows or '<tr><td colspan="4">None.</td></tr>'}
</table>
<footer>Generated by <a href="https://github.com/cloudsealed/JIT-Optimization-Engine">cloudsealed-jit</a>
— rolling-median baseline + MAD z-score.</footer>
</body>
</html>
"""
