"""Post or update a pull-request comment with a cloudsealed-jit report.

Stdlib-only (urllib) so the composite action needs no extra pip install
beyond the package itself. Finds a previous comment by its hidden marker and
edits it in place, so re-runs on the same PR don't spam the thread.
"""

from __future__ import annotations

import json
import os
import sys
import urllib.request

MARKER = "<!-- cloudsealed-jit-report -->"


def _api(method: str, url: str, token: str, body: dict | None = None) -> dict:
    data = json.dumps(body).encode() if body is not None else None
    req = urllib.request.Request(url, data=data, method=method)
    req.add_header("Authorization", f"Bearer {token}")
    req.add_header("Accept", "application/vnd.github+json")
    req.add_header("X-GitHub-Api-Version", "2022-11-28")
    with urllib.request.urlopen(req) as resp:
        return json.loads(resp.read().decode()) if resp.length != 0 else {}


def render_markdown(report: dict) -> str:
    metrics = report["metrics"]
    anomalies = report["anomalies"]
    recs = report["recommendations"][:5]

    lines = [
        MARKER,
        "## 💰 cloudsealed-jit — billing waste audit",
        "",
        report["summary"],
        "",
        f"| Waste | Avg daily cost | Stability | Anomalies |",
        f"|---|---|---|---|",
        f"| **{metrics['wastePercentage']:.1f}%** | "
        f"${metrics['averageDailyCost']:,.2f} | "
        f"{metrics['sharpeRatio']:.2f} | {len(anomalies)} |",
    ]

    if anomalies:
        lines += ["", "### Anomalies", "", "| Date | Severity | z-score | Deviation | |", "|---|---|---|---|---|"]
        for a in anomalies[:10]:
            lines.append(
                f"| {a['date']} | {a['severity']} | {a['zScore']:.1f} | "
                f"{a['deviation']:+.1f}% | {a['description']} |"
            )

    if recs:
        lines += ["", "### Top recommendations", ""]
        for r in recs:
            lines.append(f"- **{r['title']}** — ${r['potentialSavings']:,.2f}/mo, effort {r['effort']}")

    lines += ["", "_Generated by [cloudsealed-jit](https://github.com/cloudsealed/JIT-Optimization-Engine) "
                    "— rolling-median baseline + MAD z-score, method in "
                    "[METHODOLOGY.md](https://github.com/cloudsealed/JIT-Optimization-Engine/blob/main/METHODOLOGY.md)._"]
    return "\n".join(lines)


def main() -> int:
    token = os.environ["GITHUB_TOKEN"]
    report_path = os.environ["REPORT_JSON"]
    event_path = os.environ["GITHUB_EVENT_PATH"]
    repo = os.environ["GITHUB_REPOSITORY"]

    with open(event_path, encoding="utf-8") as f:
        event = json.load(f)
    pr_number = event.get("pull_request", {}).get("number")
    if pr_number is None:
        print("Not a pull_request event; skipping comment.")
        return 0

    with open(report_path, encoding="utf-8") as f:
        report = json.load(f)

    body = render_markdown(report)
    base = f"https://api.github.com/repos/{repo}"

    comments = _api("GET", f"{base}/issues/{pr_number}/comments?per_page=100", token)
    existing = next((c for c in comments if MARKER in c.get("body", "")), None)

    if existing:
        _api("PATCH", f"{base}/issues/comments/{existing['id']}", token, {"body": body})
        print(f"Updated comment {existing['id']} on PR #{pr_number}.")
    else:
        _api("POST", f"{base}/issues/{pr_number}/comments", token, {"body": body})
        print(f"Posted new comment on PR #{pr_number}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
